const fs = require("fs");
const path = require("path");

const artifact = require("../artifacts/contracts/Settla.sol/Settla.json");
const lib = path.join(__dirname, "..", "..", "web", "src", "lib");
const json = JSON.stringify(artifact.abi, null, 2);

// JSON for Node consumers (listen.js); TS `as const` so viem and wagmi infer types.
fs.writeFileSync(path.join(lib, "settla.abi.json"), json + "\n");
fs.writeFileSync(
  path.join(lib, "settla.abi.ts"),
  `// Generated by contracts/scripts/export-abi.js. Do not edit.\nexport const settlaAbi = ${json} as const;\n`,
);
console.log("ABI exported to web/src/lib");
